// match_game_angular/src/app/components/highscores/highscores.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { GameService } from '../../services/game.service';
import User from '../../model/user';

@Component({
  selector: 'app-highscores',
  templateUrl: './highscores.component.html',
  styleUrls: ['./highscores.component.css']
})
export class HighscoresComponent {
  currentUser: User;
  highScores: Array<{ id: number; user: string; score: number; completed: boolean }>;
  top10HighScores: { id: number; user: string; score: number; completed: boolean; }[] | undefined;
  userHighScores: { id: number; user: string; score: number; completed: boolean; }[] | undefined;

  constructor(private authService: AuthService, private gameService: GameService) {
    this.currentUser = {} as User;
    this.highScores = [];
  }

  ngOnInit() {
    this.fetchHighScores();
  }

  async fetchHighScores() {
    try {
      this.currentUser = await this.authService.getCurrentUser();
      const allGames = await this.gameService.getAllGames();

      const filteredGames = allGames
        .filter((score: { score: number; completed: any }) => score.score > 0 && score.completed); // Only include non-zero scores and completed games

      const orderedHighScores = filteredGames.sort((a: any, b: any) => b.score - a.score); // Re-order highest to lowest

      this.top10HighScores = orderedHighScores.slice(0, 10);
    
      this.userHighScores = orderedHighScores
        .filter((score: { user: any }) => score.user === this.currentUser.id)
        .slice(0, 3); 
      
      } catch (error) {
      console.error('Failed to fetch high scores', error);
    }
  }
}

<div class="jumbotron">
    <div class="center">
      <h1>High Scores</h1>
      <table class="table">
        <thead>
          <tr>
            <th>User ID</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let score of top10HighScores">
            <td>{{ score.user }}</td>
            <td>{{ score.score }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="jumbotron">
    <div class="center">
      <h3><strong>{{ currentUser.username }}</strong></h3>
      <table class="table">
        <thead>
          <tr>
            <th>User ID</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let score of userHighScores">
            <td>{{ score.user }}</td>
            <td>{{ score.score }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

// match_game/src/components/highscores.component.tsx
import React, { Component } from 'react';
import GameService from '../services/game.service';
import AuthService from '../services/auth.service';
import User from "../model/user";

type State = {
  currentUser: User;
  highScores: Array<{ id: number; user: string; score: number; completed: boolean }>;
};

class HighScores extends Component<{}, State> {

  constructor(props: {}) {
    super(props);
    this.state = {
      currentUser: {} as User,
      highScores: [],
    };
  }

  async componentDidMount() {
    try {
      const user = await AuthService.getCurrentUser();
      const allGames = await GameService.getAllGames();
      
      const filteredGames = allGames
        .filter((score: { score: number; completed: any; }) => score.score > 0 && score.completed); // Only include non-zero scores and completed games
  
      const orderedHighscores = filteredGames.sort((a: any, b: any) => b.score - a.score); // Re-order highest to lowest
  
      this.setState({ currentUser: user, highScores: orderedHighscores });
    } catch (error) {
      console.error('Failed to fetch high scores', error);
    }
  }

  render() {
    const { currentUser, highScores } = this.state;

    const top10HighScores = highScores.slice(0, 10);
    
    const userHighScores = highScores
      .filter((score: { user: any }) => score.user === currentUser.id)
      .slice(0, 3);

    return (
      <>
        <div className='jumbotron'>
          <div className='center'>
            <h1>High Scores</h1>
            <table className='table'>
              <thead>
                <tr>
                  <th>User ID</th>
                  <th>Score</th>
                </tr>
              </thead>
              <tbody>
                {top10HighScores.map(score => (
                  <tr key={score.id}>
                    <td>{score.user}</td>
                    <td>{score.score}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className='jumbotron'>
          <div className='center'>
            <h3><strong>{currentUser.username}</strong></h3>
            <table className='table'>
              <thead>
                <tr>
                  <th>User ID</th>
                  <th>Score</th>
                </tr>
              </thead>
              <tbody>
                {userHighScores.map(score => (
                  <tr key={score.id}>
                    <td>{score.user}</td>
                    <td>{score.score}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </>
    );
  }
}

export default HighScores;
