// match_game_angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './services/auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  isLoggedIn = false;

  constructor(private authService: AuthService) {}

  async ngOnInit() {
    this.isLoggedIn = sessionStorage['user'] ?  true : false;

    document.addEventListener('logout', this.logout);
  }

  ngOnDestroy() {
    document.removeEventListener('logout', this.logout)
  }

  logout(): void {
    this.authService.logout();
    sessionStorage.clear();
    window.location.reload();
  }
}
<div id="app">
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <ul class="navbar-nav mr-auto" routerLinkActive="active">
      <li class="nav-item">
        <a href="/" class="nav-link" routerLink="/">Home </a>
      </li> 
      <li class="nav-item">
        <a href="/games" class="nav-link" routerLink="/games">Game </a>
      </li>
      <li class="nav-item">
        <a href="/highscores" class="nav-link" routerLink="/highscores">High Scores </a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto" *ngIf="!isLoggedIn">
      <li class="nav-item">
        <a href="/login" class="nav-link" routerLink="login">Login</a>
      </li>
      <li class="nav-item">
        <a href="/register" class="nav-link" routerLink="register">Register</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto" *ngIf="isLoggedIn">
      <li class="nav-item">
        <a href="/profile" class="nav-link" routerLink="profile">Profile</a>
      </li>
      <li class="nav-item">
        <a href class="nav-link" (click)="logout()">Log out</a>
      </li>
    </ul>
  </nav>

  <div class="container">
    <router-outlet></router-outlet>
  </div>
</div>

// match_game/src/App.tsx
import { Component } from "react";
import { Routes, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";

import AuthService from "./services/auth.service";
import User from './model/user';

import Login from "./components/login.component";
import Register from "./components/register.component";
import Home from "./components/home.component";
import Profile from "./components/profile.component";
import Game from "./components/game.component";

import EventBus from "./common/EventBus";
import HighScores from "./components/highscores.component";

type Props = {};

type State = {
  currentUser: User | undefined
}

class App extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.logOut = this.logOut.bind(this);

    this.state = {
      currentUser: undefined,
    };
  }

  async componentDidMount() {
    const user = await AuthService.getCurrentUser();
  
    if (user) {
      this.setState({
        currentUser: user as User
      });
    }
  
    EventBus.on("logout", this.logOut);
  }
  

  componentWillUnmount() {
    EventBus.remove("logout", this.logOut);
  }

  logOut() {
    AuthService.logout();
    this.setState({
      currentUser: undefined,
    });
  }

  render() {
    const { currentUser } = this.state;

    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <div className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to={"/home"} className="nav-link">
                Home
              </Link>
            </li>

            {currentUser && (
              <li className="nav-item">
                <Link to={"/game"} className="nav-link">
                  Game
                </Link>
              </li>
            )}

            {currentUser && (
              <li className="nav-item">
                <Link to={"/highscores"} className="nav-link">
                  High Scores
                </Link>
              </li>
            )}
          </div>

          {currentUser ? (
            <div className="navbar-nav ml-auto">
              <li className="nav-item">
                <Link to={"/profile"} className="nav-link">
                  Profile
                </Link>
              </li>
              <li className="nav-item">
                <a href="/login" className="nav-link" onClick={this.logOut}>
                  Log out
                </a>
              </li>
            </div>
          ) : (
            <div className="navbar-nav ml-auto">
              <li className="nav-item">
                <Link to={"/login"} className="nav-link">
                  Login
                </Link>
              </li>

              <li className="nav-item">
                <Link to={"/register"} className="nav-link">
                  Register
                </Link>
              </li>
            </div>
          )}
        </nav>

        <div className="container mt-3">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/home" element={<Home />} />
            <Route path="/login" element={<Login />} />
            <Route path="/register" element={<Register />} />
            <Route path="/profile" element={<Profile />} />
            <Route path="/game" element={<Game/>} />
            <Route path="/highscores" element={<HighScores/>} />
          </Routes>
        </div>
      </div>
    );
  }
}

export default App;
